--

-- Database: 'cse 340 project', .public schema

-- Assignment 2, Task 2

--



-- Create account_type data type



DROP TYPE IF EXISTS public.account_type;



CREATE TYPE public.account_type AS ENUM(



    'Client',



    'Employee',



    'Admin');



-- Table structure for table `classification`



CREATE TABLE public.classification (



    classification_id INT GENERATED BY DEFAULT AS IDENTITY,



    classification_name CHARACTER VARYING NOT NULL,



    CONSTRAINT classification_pk PRIMARY KEY (classification_id)



);



-- Table structure for table `inventory`



CREATE TABLE IF NOT EXISTS public.inventory



(



    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,



    inv_make character varying NOT NULL,



    inv_model character varying NOT NULL,



    inv_year character(4) NOT NULL,



    inv_description text NOT NULL,



    inv_image character varying NOT NULL,



    inv_thumbnail character varying NOT NULL,



    inv_price numeric(9, 0) NOT NULL,



    inv_miles integer NOT NULL,



    inv_color character varying NOT NULL,



    classification_id integer NOT NULL,



    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)



);







-- Table structure for table `inventory`



CREATE TABLE IF NOT EXISTS public.inventory



(



    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,



    inv_make character varying NOT NULL,



    inv_model character varying NOT NULL,



    inv_year character(4) NOT NULL,



    inv_description text NOT NULL,



    inv_image character varying NOT NULL,



    inv_thumbnail character varying NOT NULL,



    inv_price numeric(9, 0) NOT NULL,



    inv_miles integer NOT NULL,



    inv_color character varying NOT NULL,



    classification_id integer NOT NULL,



    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)



);







-- 1. Remove the existing type if it's causing conflicts



DROP TYPE IF EXISTS public.account_type CASCADE;







-- 2. Re-create the type via script to ensure no hidden formatting issues



CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');







-- 3. Create the table using the freshly scripted type



CREATE TABLE IF NOT EXISTS public.account



(



    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,



    account_firstname character varying NOT NULL,



    account_lastname character varying NOT NULL,



    account_email character varying NOT NULL,



    account_password character varying NOT NULL,



    account_type public.account_type NOT NULL



        DEFAULT 'Client'::public.account_type,



    CONSTRAINT account_pkey PRIMARY KEY (account_id)



);

--